var translations = {
    en: {
        title: "Welcome to Star Wars Universe",
        home: "Home",
        about: "About the Saga",
        characters: "Characters",
        ships: "Spaceships",
        contact: "Contact",
        welcome: "Explore the galaxy far, far away...",
        footer: "&copy; 2024 Star Wars Universe",
        home_title: "Star Wars",
        home_welcome_text: "«Star Wars» is an epic story of the struggle between light and darkness, which takes us to the amazing world of space. Immerse yourself in the thrilling adventures of Jedi, Sith, smugglers and heroes from all corners of the galaxy.",
        home_posters: "Movie covers",
        Luke_Skywalker_h3: "Luke Skywalker",
        home_Luke_Skywalker_p: "Luke Skywalker is one of the main characters in the Star Wars universe, a Jedi, the son of Naboo Senator Padmé Amidala Naberria and Jedi Knight Anakin Skywalker. He is the older twin brother of Leia Organa Solo. Mark Hamill played Luke in the original trilogy and the sequel trilogy.",
        Leia_Organa_h3: "Princess Leia",
        home_Leia_Organa_p: "Leia Organa Solo (born Leia Amidala Skywalker) was the daughter of Jedi Knight Anakin Skywalker and Senator Padmé Amidala Naberrie, and the twin sister of Luke Skywalker. After birth, she was adopted by Bail Organa and Queen Breha, making her the Princess of Alderaan.",
        about_title: "About the saga",
        about_saga_h1: "About the saga",
        about_introduction_to_the_Saga_h2: "Introduction to the Saga",
        about_introduction_to_the_Saga_p: "Star Wars is an epic journey that began in 1977 with a dream from George Lucas. The saga tells the story of the eternal struggle between light and dark, heroes and villains, and the art of magic and technology that has captivated generations of fans around the world.",
        about_history_of_Star_Wars_h2: "History of Star Wars",
        about_history_of_Star_Wars_p: "Check out the exciting trailer for the original trilogy:",
        about_timeline_of_saga_h2: "Chronology and structure of the saga",
        about_timeline_of_saga_p: "The Star Wars universe spans nine episodes, telling the story of the Skywalker family. In addition to the main saga, the Star Wars world includes spin-offs such as Rogue One, Solo, and TV series such as The Mandalorian and Ahsoka.",
        about_mythology_and_philosophy_h2: "Mythology and Philosophy",
        about_mythology_and_philosophy_p: "The Force unites all life. It is the key to understanding the duality of good and evil, balance and struggle. George Lucas drew inspiration from philosophies and myths to create a unique world in which everyone can find something for themselves.",
        about_cult_music_h2: "Cult music",
        about_cult_music_p: "Immerse yourself in the galactic atmosphere with John Williams' famous composition:",
        about_impact_on_culture_h2: "Impact on culture",
        about_impact_on_culture_p: "Star Wars ushered in a new era of cinema, introducing technologies that are still used in films today. Phrases from the saga, such as “May the Force be with you” and “I am your father,” have become part of popular culture.",
        about_fan_culture_h2: "Fan culture",
        about_fan_culture_p: "Since the release of the first film, millions of fans have come together to share stories, create costumes, and celebrate Star Wars Day on May 4. The fan community has become an integral part of this legendary saga.",
        about_future_of_franchise_h2: "The Future of Franchising",
        about_future_of_franchise_p: "The world of Star Wars continues to grow. New films, TV series and games promise even more exciting stories that will reveal new facets of a galaxy far, far away.",
        characters_title: "Characters",
        characters_characters_h1: "Characters",
        characters_introduction_to_characters_h2: "Introduction to characters",
        characters_introduction_to_characters_p: "Star Wars is famous for its memorable characters, each with their own unique history and traits. Jedi, Sith, smugglers, droids and other heroes have become symbols of struggle, hope and adventure.",
        characters_key_characters_h2: "Key characters",
        characters_key_characters_Luke_Skywalker_p: "Luke Skywalker, a Force-sensitive human male, was a legendary Jedi Master who fought in the Galactic Civil War during the reign of the Galactic Empire. Along with his comrades, Princess Leia Organa and General Han Solo, Skywalker served as a revolutionary for the Alliance to Restore the Republic, an organization that sought to bring down the Galactic Empire and restore democracy. After the war, Skywalker became a living legend and is remembered as one of the greatest Jedi in galactic history.",
        characters_audio_caption_Luke_Skywalker_p: "Luke Skywalker vs Dark Troopers.",
        characters_Darth_Vader_h3: "Darth Vader",
        characters_Darth_Vader_p: "Darth Vader (formerly Anakin Skywalker) is an iconic character in the Star Wars universe. He was a powerful Jedi, but succumbed to the dark side of the Force, becoming a Sith and the right hand of Emperor Palpatine. Characterized by his sinister black armor, mask with breathing apparatus and menacing voice. A talented pilot and master of the lightsaber, Vader is known for his cruelty and inflexibility. However, within him there remains a conflict between good and evil, which leads to his redemption at the end of the saga.",
        characters_Leia_Organa_p: "The brave and intelligent leader of the Rebel Alliance, the daughter of Padmé Amidala and Anakin Skywalker, and the sister of Luke Skywalker. She has a strong character, a sharp mind, and natural leadership. Leia played a key role in the fight against the Galactic Empire, preserving the data on the Death Star. Her courage, dedication to the cause of freedom, and ability to inspire make her one of the central figures of the saga.",
        characters_Han_Solo_h3: "Han Solo",
        characters_Han_Solo_p: "A fearless but cynical smuggler who later becomes a hero of the Rebel Alliance. Pilot of the famous starship «Millennium Falcon» and partner of the faithful Wookiee Chewbacca. At first motivated by personal gain, but friendship with Luke, Leia and other events reveal his dedication and courage. His cheeky charm, sense of humor and determination make him one of the most beloved characters.",
        characters_Droids_h2: "Droids",
        characters_R2_D2_h3: "R2-D2",
        characters_R2_D2_p: "A compact yet incredibly useful astromech droid, R2-D2 has a witty personality and is fearless in helping his friends, often rescuing them from dangerous situations. He has witnessed key events in galactic history, beginning with the Clone Wars. The droid is known for his mastery of repair, navigation, and hacking systems, as well as his strong bond with C-3PO.",
        characters_C_3PO_h3: "C-3PO",
        characters_C_3PO_p: "A humanoid protocol droid created by Anakin Skywalker, C-3PO is a master of etiquette and translation, fluent in millions of languages. Despite his tendency to worry and talk too much, he remains a loyal companion and often makes unexpected contributions to the success of missions. His interactions with R2-D2 add humor to the saga.",
        characters_phrases_that_change_all_h2: "Phrases that changed everything",
        characters_phrases_that_change_all_p: "«I am your father» is one of the most famous phrases in the history of cinema.",
        characters_quotes_moments_h2: "Quotes and Moments",
        characters_quotes_moments_p: "Few films can boast such iconic moments and lines as:",
        characters_list_of_quotes_moments_quote_1_li: `<strong>"May the Force be with you."</strong> — One of the most recognizable phrases of the franchise, spoken by Jedi and their allies.`,
        characters_list_of_quotes_moments_quote_2_li: `<strong>"Help me, Obi-Wan Kenobi. You're my only hope."</strong> — Leia`,
        characters_list_of_quotes_moments_quote_3_li: `<strong>"Remember: Fear is the path to the dark side"</strong> - (Episode I: The Phantom Menace)<br>Yoda explains how fear leads to suffering.`,
        characters_list_of_quotes_moments_quote_4_li: `<strong>Opening Titles</strong> - Each part is accompanied by text scrolling into the starry space, with epic music by John Williams.`,
        characters_list_of_quotes_moments_quote_5_li: `<strong>Destruction of the Death Star</strong> - (Episode IV and Episode VI)<br>Luke destroys the first Death Star, and later the Rebels destroy the second.`,
        characters_list_of_quotes_moments_quote_6_li: `<strong>Duel on Mustafar</strong> - (Episode III: Revenge of the Sith)<br>An epic battle between Obi-Wan and Anakin on the lava planet, where the latter fully becomes Darth Vader.`,
        characters_list_of_quotes_moments_quote_7_li: `<strong>The Appearance of Darth Maul with a Double-Bladed Lightsaber</strong> - (Episode I: The Phantom Menace)<br>An impressive moment showcasing the power of the Sith.`,
        characters_list_of_quotes_moments_quote_8_li: `<strong>The Death of Darth Vader and Luke's Salvation</strong> - (Episode VI: Return of the Jedi)<br>Vader saves Luke from the Emperor and dies, redeeming himself.`,
        ships_title: `Spaceships`,
        ships_spaceships_h1: `Spaceships`,
        ships_nav_ships_fighters_a: `Fighters`,
        ships_nav_ships_freighters_a: `Cargo ships`,
        ships_nav_ships_destroyers_a: `Star Destroyers`,
        ships_fighters_fighters_h2: `Fighters`,
        ships_fighters_X_Wing_h2: `X-Wing`,
        ships_fighters_X_Wing_p: `<strong>Description:</strong> X-wing fighters were designed 
        for dogfights and long-duration missions. During the Galactic 
        Civil War, the Rebel Alliance used X-wing fighter models such as the T-65B X-wing 
        and T-65C-A2 X-wing fighter in many 
        battles, deploying X-wings in battles such as the Attack on Lothal, 
        the Battle of Yavin, the Battle of Endor, and the Battle of Jakku.`,
        ships_fighters_X_Wing_length_p: `<strong>Length:</strong> 12.5 m`,
        ships_fighters_X_Wing_armament_p: `<strong>Armament:</strong> Laser cannons, proton torpedoes`,
        ships_fighters_TIE_Fighter_h3: `TIE-Fighter`,
        ships_fighters_TIE_Fighter_p: `<strong>Description:</strong> TIE/ln space superiority fighter,
        commonly called TIE/LN fighter, TIE/line fighter,
        a TIE or T/F fighter, was a standard Imperial fighter,
        which could be seen in huge quantities throughout
        most of the Galactic Civil War and more. sometimes,
        because of their distinctive form, the pilots of the rebels and the New Republic
        they called this ship "eyeballs".`,
        ships_fighters_TIE_Fighter_length_p: `<strong>Length:</strong> 8.99 m`,
        ships_fighters_TIE_Fighter_armament_p: `<strong>Weapons:</strong> Laser cannons`,
        ships_freighters_freighters_h2: `Cargo ships`,
        ships_freighters_Millennium_Falcon_h3: `Millennium Falcon`,
        ships_freighters_Millennium_Falcon_p: `<strong>Description:</strong> The Millennium Falcon, originally designated YT 492727ZED and formerly known as the Stellar Envoy, and registered or known by various aliases, was a Corellian YT-1300 light freighter built approximately 60 years before the Battle of Yavin. Earning a legendary status under its ownership, the ship is best known for being used by smugglers Han Solo and Chewbacca before, during, and after the Galactic Civil War.`,
        ships_freighters_Millennium_Falcon_length_p: `<strong>Length:</strong> 34.75 m`,
        ships_freighters_Millennium_Falcon_armament_p: `<strong>Feature:</strong> Kessel Run in 12 parsecs.`,
        ships_destroyers_destroyers_h2: `Star Destroyers`,
        ships_destroyers_Imperial_Star_Destroyer_h3: `Imperial Star Destroyer`,
        ships_destroyers_Imperial_Star_Destroyer_p: `<strong>Description:</strong> The flagship of the Imperial Navy and a symbol of Imperial might. These massive capital ships are used to enforce the Emperor's will, support Imperial-backed governments, and act as mobile headquarters for senior Imperial commanders. A single Star Destroyer is considered sufficient to crush a rebellious planet, though major industrial worlds can be attacked by a fleet of six Star Destroyers with support cruisers and supply vessels. Deep-seated survival bunkers are considered the last refuge in the event of a planetary bombardment by Imperial Star Destroyers.`,
        ships_destroyers_Imperial_Star_Destroyer_length_p: `<strong>Length:</strong> 1,600 m`,
        ships_destroyers_Imperial_Star_Destroyer_armament_p: `<strong>Weapons:</strong> Laser turrets, ion cannons, tractor beam`,
        contacts_title: `Contacts`,
        contacts_contacts_h1: `Contacts`,
        contacts_contact_us_h2: `Contact us`,
        contacts_contact_us_p: `If you have any questions or suggestions, please email us at <a href="playeralex2006@gmail.com">playeralex2006@gmail.com</a> or find us on social media.`,
        
    },
    ru: {
        title: "Добро пожаловать в мир Звёздных войн",
        home: "Главная",
        about: "О саге",
        characters: "Персонажи",
        ships: "Космические корабли",
        contact: "Контакты",
        welcome: "Добро пожаловать в далёкую-далёкую галактику...",
        footer: "&copy; 2024 Мир Звёздных войн",
        home_title: "Звёздные войны",
        home_welcome_text: `«Звёздные войны» — это эпическая история борьбы света и тьмы, которая переносит нас в удивительный мир космоса. 
                    Погрузитесь в захватывающие приключения джедаев, ситхов, контрабандистов и героев со всех концов галактики.`,
        home_posters: "Обложки фильмов",
        Luke_Skywalker_h3: "Люк Скайуокер",
        home_Luke_Skywalker_p: `Люк Скайуо́кер (англ. Luke Skywalker) — один из главных персонажей вселенной 
                            «Звёздные войны», джедай, сын сенатора с Набу Падме Амидалы Наберри
                             и рыцаря-джедая Энакина Скайуокера. Старший брат-близнец Леи Органы Соло. 
                             В оригинальной трилогии и трилогии-сиквеле в роли Люка снялся Марк Хэмилл.`,
        Leia_Organa_h3: "Принцесса Лея",
        home_Leia_Organa_p: "Лея Органа-Соло (англ. Leia Organa Solo) (имя при рождении — Лея Амидала Скайуокер) — дочь рыцаря-джедая Энакина Скайуокера и сенатора Падме Амидалы Наберри, а также сестра-близнец Люка Скайуокера. После рождения её удочерили Бейл Органа и королева Бреха, сделав её принцессой Альдераана.",
        about_title: "О саге",
        about_saga_h1: "О саге",
        about_introduction_to_the_Saga_h2: "Введение в сагу",
        about_introduction_to_the_Saga_p: "«Звёздные войны» — это эпическое путешествие, начавшееся в 1977 году с мечты Джорджа Лукаса. Сага рассказывает о вечной борьбе света и тьмы, героях и злодеях, об искусстве магии и технологий, которое завораживает поколения фанатов по всему миру.",
        about_history_of_Star_Wars_h2: "История «Звёздных Войн»",
        about_history_of_Star_Wars_p: "Посмотрите захватывающий трейлер оригинальной трилогии:",
        about_timeline_of_saga_h2: "Хронология и структура саги",
        about_timeline_of_saga_p: "Вселенная «Звёздных войн» охватывает девять эпизодов, рассказывая историю семьи Скайуокеров. Помимо основной саги, мир «Звёздных войн» включает спин-оффы, такие как «Изгой-один», «Соло», и сериалы, например «Мандалорец» и «Асока».",
        about_mythology_and_philosophy_h2: "Мифология и философия",
        about_mythology_and_philosophy_p: "Сила объединяет все живое. Она — ключ к пониманию дуальности добра и зла, баланса и борьбы. Джордж Лукас черпал вдохновение из философий и мифов, чтобы создать уникальный мир, в котором каждый может найти что-то своё.",
        about_cult_music_h2: "Культовая музыка",
        about_cult_music_p: "Погрузитесь в атмосферу галактики с помощью знаменитой композиции Джона Уильямса:",
        about_impact_on_culture_h2: "Влияние на культуру",
        about_impact_on_culture_p: "«Звёздные войны» открыли новую эру кинематографа, подарив миру технологии, которые до сих пор используются в фильмах. Фразы из саги, такие как «Да пребудет с тобой Сила» и «Я твой отец», стали частью массовой культуры.",
        about_fan_culture_h2: "Фанатская культура",
        about_fan_culture_p: "С момента выхода первого фильма миллионы поклонников объединяются, чтобы делиться своими историями, создавать костюмы и отмечать День «Звёздных войн» — 4 мая. Фан-сообщество стало неотъемлемой частью этой легендарной саги.",
        about_future_of_franchise_h2: "Будущее франшизы",
        about_future_of_franchise_p: "Мир «Звёздных войн» продолжает расти. Новые фильмы, сериалы и игры обещают ещё больше увлекательных историй, которые раскроют новые грани далёкой-далёкой галактики.",
        characters_title: "Персонажи",
        characters_characters_h1: "Персонажи",
        characters_introduction_to_characters_h2: "Введение в персонажей",
        characters_introduction_to_characters_p: "«Звёздные войны» славятся своими запоминающимися персонажами, каждый из которых имеет уникальную историю и черты. Джедаи, ситхи, контрабандисты, дроиды и другие герои стали символами борьбы, надежды и приключений.",
        characters_key_characters_h2: "Ключевые персонажи",
        characters_key_characters_Luke_Skywalker_p: "Люк Скайуокер, чувствительный к Силе человек мужского пола, был легендарным мастером-джедаем, сражавшимся в Галактической гражданской войне во время правления Галактической Империи. Вместе со своими товарищами, принцессой Леей Органой и генералом Ханом Соло, Скайуокер служил революционером на стороне Альянса за восстановление Республики — организации, стремившейся к падению Галактической Империи и восстановлению демократии. После войны Скайуокер стал живой легендой и запомнился как один из величайших джедаев в истории галактики.",
        characters_audio_caption_Luke_Skywalker_p: "Люк Скайуокер против Тёмных штурмовиков.",
        characters_Darth_Vader_h3: "Дарт Вейдер",
        characters_Darth_Vader_p: "Дарт Вейдер (в прошлом – Энакин Скайуокер) — культовый персонаж во вселенной «Звёздных войн». Он был могущественным джедаем, но, поддавшись тёмной стороне Силы, стал ситхом и правой рукой Императора Палпатина. Характеризуется зловещей чёрной бронёй, маской с дыхательным аппаратом и грозным голосом. Будучи талантливым пилотом и мастером владения световым мечом, Вейдер известен своей жестокостью и непреклонностью. Внутри него, однако, остаётся конфликт между добром и злом, что приводит к его искуплению в финале саги.",
        characters_Leia_Organa_p: "Храбрая и умная лидер Повстанческого Альянса, дочь Падме Амидалы и Энакина Скайуокера, а также сестра Люка Скайуокера. Обладает сильным характером, острым умом и природным лидерством. Лея сыграла ключевую роль в борьбе против Галактической Империи, сохранив данные о Звезде Смерти. Её смелость, преданность делу свободы и способность вдохновлять делают её одной из центральных фигур саги.",
        characters_Han_Solo_h3: "Хан Соло",
        characters_Han_Solo_p: "Бесстрашный, но циничный контрабандист, который позже становится героем Повстанческого Альянса. Пилот знаменитого космического корабля «Тысячелетний сокол» и напарник верного вуки Чубакки. Сначала руководствуется личной выгодой, но дружба с Люком, Лея и другие события раскрывают его преданность делу и смелость. Его дерзкий шарм, чувство юмора и решимость делают его одним из самых любимых персонажей.",
        characters_Droids_h2: "Дроиды",
        characters_R2_D2_h3: "Р2-Д2",
        characters_R2_D2_p: "Компактный, но невероятно полезный астромеханический дроид. Р2-Д2 обладает остроумным характером и бесстрашно помогает своим друзьям, часто спасая их из опасных ситуаций. Он был свидетелем ключевых событий в истории галактики, начиная с Войн Клонов. Дроид известен своим мастерством в ремонте, навигации и взломе систем, а также крепкой связью с C-3PO.",
        characters_C_3PO_h3: "C-3PO",
        characters_C_3PO_p: "Человекообразный протокольный дроид, созданный Энакином Скайуокером. C-3PO — мастер этикета и перевода, владеющий миллионами языков. Несмотря на его склонность к излишнему беспокойству и болтливости, он остаётся верным спутником и часто вносит неожиданный вклад в успех миссий. Его взаимодействия с Р2-Д2 добавляют юмора в сагу.",
        characters_phrases_that_change_all_h2: "Фразы, которые изменили всё",
        characters_phrases_that_change_all_p: "«Я твой отец» — одна из самых известных фраз в истории кино.",
        characters_quotes_moments_h2: "Цитаты и моменты",
        characters_quotes_moments_p: "Немногие фильмы могут похвастаться такими знаковыми моментами и фразами, как:",
        characters_list_of_quotes_moments_quote_1_li: `<strong>"Да пребудет с тобой Сила."</strong> — Одна из самых узнаваемых фраз франшизы, произносимая джедаями и их союзниками.`,
        characters_list_of_quotes_moments_quote_2_li: `<strong>"Помоги мне, Оби-Ван Кеноби. Ты моя последняя надежда."</strong> — Лея`,
        characters_list_of_quotes_moments_quote_3_li: `<strong>"Помни: страх — это путь на тёмную сторону"</strong> - (Эпизод I: Скрытая угроза)<br> Йода объясняет, как страх приводит к страданиям.`,
        characters_list_of_quotes_moments_quote_4_li: `<strong>Открывающие титры</strong> - Каждую часть сопровождает текст, уходящий в звёздное пространство, с эпической музыкой Джона Уильямса.`,
        characters_list_of_quotes_moments_quote_5_li: `<strong>Разрушение Звезды Смерти</strong> - (Эпизод IV и Эпизод VI)<br> Люк уничтожает первую Звезду Смерти, а позже Повстанцы — вторую.`,
        characters_list_of_quotes_moments_quote_6_li: `<strong>Дуэль на Мустафаре</strong> - (Эпизод III: Месть ситхов)<br> Эпическая битва между Оби-Ваном и Энакином на лавовой планете, где последний окончательно становится Дартом Вейдером.`,
        characters_list_of_quotes_moments_quote_7_li: `<strong>Появление Дарта Мола с двойным световым мечом</strong> - (Эпизод I: Скрытая угроза)<br> Впечатляющий момент, подчёркивающий мощь ситха.`,
        characters_list_of_quotes_moments_quote_8_li: `<strong>Смерть Дарта Вейдера и спасение Люка</strong> - (Эпизод VI: Возвращение джедая)<br> Вейдер спасает Люка от Императора и умирает, искупив свои грехи.`,
        ships_title: `Космические корабли`,
        ships_spaceships_h1: `Космические корабли`,
        ships_nav_ships_fighters_a: `Истребители`,
        ships_nav_ships_freighters_a: `Грузовые корабли`,
        ships_nav_ships_destroyers_a: `Звёздные разрушители`,
        ships_fighters_fighters_h2: `Истребители`,
        ships_fighters_X_Wing_h2: `X-Wing/Крестокрыл`,
        ships_fighters_X_Wing_p: `<strong>Описание:</strong> Истребители X-wing были разработаны 
        для воздушных боев и длительных миссий. Во время Галактической 
        гражданской войны Альянс повстанцев использовал модели истребителей X-wing, 
        такие как истребитель T-65B X-wing и T-65C-A2 X-wing во многих 
        сражениях, развертывая X-wing в таких сражениях, как Атака на Лотал, 
        Битва при Явине, Битва при Эндоре и Битва за Джакку.`,
        ships_fighters_X_Wing_length_p: `<strong>Длина:</strong> 12,5 м`,
        ships_fighters_X_Wing_armament_p: `<strong>Вооружение:</strong> Лазерные пушки, протонные торпеды`,
        ships_fighters_TIE_Fighter_h3: `TIE-Истребитель/СИД-Истребитель`,
        ships_fighters_TIE_Fighter_p: `<strong>Описание:</strong> Истребитель космического превосходства TIE/ln, 
        обычно называемый истребителем TIE/LN, истребителем TIE/line, 
        истребителем TIE или T/F, был стандартным имперским истребителем, 
        который можно было увидеть в огромных количествах на протяжении 
        большей части Галактической гражданской войны и далее. Иногда, 
        из-за их отличительной формы, пилоты повстанцев и Новой Республики 
        называли этот корабль «глазными яблоками».`,
        ships_fighters_TIE_Fighter_length_p: `<strong>Длина:</strong> 8,99 м`,
        ships_fighters_TIE_Fighter_armament_p: `<strong>Вооружение:</strong> Лазерные пушки`,
        ships_freighters_freighters_h2: `Грузовые корабли`,
        ships_freighters_Millennium_Falcon_h3: `Тысячелетний Сокол`,
        ships_freighters_Millennium_Falcon_p: `<strong>Описание:</strong> Тысячелетний сокол, первоначально обозначенный как YT 492727ZED и ранее 
        известный как Stellar Envoy, и зарегистрированный или известный под различными псевдонимами, был 
        кореллианским легким грузовым судном YT-1300, построенным около 60 лет до битвы при Явине. Заработав 
        легендарный статус под своим владением, корабль наиболее известен тем, что использовался 
        контрабандистами Ханом Соло и Чубаккой до, во время и после Галактической гражданской войны.`,
        ships_freighters_Millennium_Falcon_length_p: `<strong>Длина:</strong> 34,75 м`,
        ships_freighters_Millennium_Falcon_armament_p: `<strong>Особенность:</strong> Кессельский пробег за 12 парсеков.`,
        ships_destroyers_destroyers_h2: `Звёздные разрушители`,
        ships_destroyers_Imperial_Star_Destroyer_h3: `Имперский Звездный Разрушитель`,
        ships_destroyers_Imperial_Star_Destroyer_p: `<strong>Описание:</strong> Главный  военный корабль Имперского флота и символ 
        Имперской мощи.Эти огромные капитальные корабли используются для исполнения воли Императора, 
        поддержки поддерживаемых Империей правительств и выступают в качестве 
        мобильных штабов для старших имперских командиров. Считается, что одного Звездного Разрушителя достаточно, 
        чтобы сокрушить мятежную планету, хотя крупные индустриальные миры могут быть 
        атакованы флотом из шести Звездных Разрушителей с крейсерами поддержки и судами 
        снабжения. Глубоко залегающие бункеры для выживания считаются последним убежищем 
        в случае планетарной бомбардировки Имперскими Звездными Разрушителями.`,
        ships_destroyers_Imperial_Star_Destroyer_length_p: `<strong>Длина:</strong> 1,600 м`,
        ships_destroyers_Imperial_Star_Destroyer_armament_p: `<strong>Вооружение:</strong> Лазерные турели, ионные пушки, тяговый луч`,
        contacts_title: `Контакты`,
        contacts_contacts_h1: `Контакты`,
        contacts_contact_us_h2: `Свяжитесь с нами`,
        contacts_contact_us_p: `Если у вас есть вопросы или предложения, напишите нам по почте <a href="playeralex2006@gmail.com">playeralex2006@gmail.com</a> или найдите нас в соцсетях.`,

    },
    uk: {
        title: "Ласкаво просимо до Всесвіту Зоряних Війн",
        home: "Головна",
        about: "Про сагу",
        characters: "Персонажі",
        ships: "Космічні кораблі",
        contact: "Контакти",
        welcome: "Досліджуйте далеку-далеку галактику...",
        footer: "&copy; 2024 Всесвіт Зоряних Війн",
        home_title: "Зоряні війни",
        home_welcome_text: "«Зоряні війни» - це епічна історія боротьби між світлом і темрявою, яка переносить нас в дивовижний світ космосу. Пориньте в захоплюючі пригоди джедаїв, ситхів, контрабандистів і героїв з усіх куточків галактики.",
        home_posters: "Обкладинки фільмів",
        Luke_Skywalker_h3: "Люк Скайуокер",
        home_Luke_Skywalker_p: "Люк Скайуокер (англ. Luke Skywalker) - один з головних героїв всесвіту «Зоряних воєн», джедай, син сенатора з Набу Падме Амідали Нарберії Найт-джедая Енакіна Скайвокера. Старший брат-близнюк Лія Органи Соло. В оригінальній трилогії і трилогії сиквелів Марк Хемілл зіграв Люка.",
        Leia_Organa_h3: "Принцеса Лея",
        home_Leia_Organa_p: "Лея Органа-Соло (англ. Leia Organa Solo) (ім'я при народженні - Лея Амідала Скайуокер) - дочка лицаря-джеда Енакіна Скайуокера та сенатора Падме Амідали Наберрі, а також сестра-близнюка Люка Скайуокера. Після народження її удочерили Бейл Органа та королева Бреха, зробивши її принцесою Альдераана.",
        about_title: "Про сагу",
        about_saga_h1: "Про сагу",
        about_introduction_to_the_Saga_h2: "Введення в сагу",
        about_introduction_to_the_Saga_p: "«Зоряні війни» - це епічна подорож, що почалася в 1977 році з мрії Джорджа Лукаса. Сага розповідає про вічну боротьбу світла і темряви, героїв і лиходіїв, про мистецтво магії та технологій, яке зачаровує покоління фанатів у всьому світі.",
        about_history_of_Star_Wars_h2: "Історія «Зоряних Війн»",
        about_history_of_Star_Wars_p: "Подивіться захоплюючий трейлер оригінальної трилогії:",
        about_timeline_of_saga_h2: "Хронологія та структура саги",
        about_timeline_of_saga_p: "Всесвіт «Зоряних війн» охоплює дев'ять епізодів, розповідаючи історію сім'ї Скайуокерів. Крім основної саги, світ «Зоряних воєн» включає спін-офи, такі як «Ізгой-один», «Соло», та серіали, наприклад «Мандалорець» та «Асока».",
        about_mythology_and_philosophy_h2: "Міфологія та філософія",
        about_mythology_and_philosophy_p: "Сила поєднує все живе. Вона - ключ до розуміння дуальності добра і зла, балансу та боротьби. Джордж Лукас черпав натхнення з філософій та міфів, щоб створити унікальний світ, у якому кожен може знайти щось своє.",
        about_cult_music_h2: "Культова музика",
        about_cult_music_p: "Пориньте в атмосферу галактики за допомогою знаменитої композиції Джона Вільямса:",
        about_impact_on_culture_h2: "Вплив на культуру",
        about_impact_on_culture_p: "«Зоряні війни» відкрили нову еру кінематографа, подарувавши світові технології, які досі використовуються у фільмах. Фрази з саги, такі як «Нехай буде з тобою Сила» і «Я твій батько», стали частиною масової культури.",
        about_fan_culture_h2: "Фанатська культура",
        about_fan_culture_p: "З моменту виходу першого фільму мільйони шанувальників поєднуються, щоб ділитися своїми історіями, створювати костюми та відзначати День «Зоряних війн» — 4 травня. Фан-спільнота стала невід'ємною частиною цієї легендарної саги.",
        about_future_of_franchise_h2: "Майбутнє франшизи",
        about_future_of_franchise_p: "Світ «Зоряних війн» продовжує зростати. Нові фільми, серіали та ігри обіцяють ще більше захоплюючих історій, які розкриють нові грані далекої галактики.",
        characters_title: "Персонажі",
        characters_characters_h1: "Персонажі",
        characters_introduction_to_characters_h2: "Введення у персонажів",
        characters_introduction_to_characters_p: "«Зоряні війни» славляться своїми персонажами, що запам'ятовуються, кожен з яких має унікальну історію і риси. Джедаї, сітхи, контрабандисти, дроїди та інші герої стали символами боротьби, надії та пригод.",
        characters_key_characters_h2: "Ключові персонажі",
        characters_key_characters_Luke_Skywalker_p: "Люк Скайуокер, чутлива до Силі людина чоловічої статі, був легендарним майстром-джедаєм, який воював у Галактичній громадянській війні під час правління Галактичної Імперії. Разом зі своїми товаришами, принцесою Леєю Органою та генералом Ханом Соло, Скайуокер служив революціонером на боці Альянсу за відновлення Республіки — організації, яка прагнула падіння Галактичної Імперії та відновлення демократії. Після війни Скайуокер став живою легендою і запам'ятався як один із найбільших джедаїв в історії галактики.",
        characters_audio_caption_Luke_Skywalker_p: "Люк Скайуокер проти темних штурмовиків.",
        characters_Darth_Vader_h3: "Дарт Вейдер",
        characters_Darth_Vader_p: "Дарт Вейдер (у минулому – Енакін Скайуокер) – культовий персонаж у всесвіті «Зоряних війн». Він був могутнім джедаєм, але, піддавшись темній стороні Сили, став сітхом та правою рукою Імператора Палпатіна. Характеризується зловісною чорною бронею, маскою з дихальним апаратом та грізним голосом. Будучи талановитим пілотом і майстром володіння світловим мечем, Вейдер відомий своєю жорстокістю та непохитністю. Усередині нього, однак, залишається конфлікт між добром та злом, що призводить до його викуплення у фіналі саги.",
        characters_Leia_Organa_p: "Хоробра та розумна лідер Повстанського Альянсу, дочка Падме Амідали та Енакіна Скайуокера, а також сестра Люка Скайуокера. Має сильний характер, гострий розум і природне лідерство. Лея відіграла ключову роль у боротьбі проти Галактичної Імперії, зберігши дані про Зірку Смерті. Її сміливість, відданість справі свободи та здатність надихати роблять її однією з центральних постатей саги.",
        characters_Han_Solo_h3: "Хан Соло",
        characters_Han_Solo_p: "Безстрашний, але цинічний контрабандист, який згодом стає героєм Повстанського Альянсу. Пілот знаменитого космічного корабля «Тисячолітній сокіл» та напарник вірного вука Чубакки. Спочатку керується особистою вигодою, але дружба з Люком, Лея та інші події розкривають його відданість справі та сміливість. Його зухвалий шарм, почуття гумору та рішучість роблять його одним із найулюбленіших персонажів.",
        characters_Droids_h2: "Дроїди",
        characters_R2_D2_h3: "Р2-Д2",
        characters_R2_D2_p: "Компактний, але неймовірно корисний астромеханічний дроїд. Р2-Д2 має дотепний характер і безстрашно допомагає своїм друзям, часто рятуючи їх із небезпечних ситуацій. Він був свідком ключових подій історії галактики, починаючи з Войн Клонів. Дроїд відомий своєю майстерністю в ремонті, навігації та зламі систем, а також міцним зв'язком з C-3PO.",
        characters_C_3PO_h3: "C-3PO",
        characters_C_3PO_p: "Людиноподібний протокольний дроїд створений Енакіном Скайуокером. C-3PO - майстер етикету та перекладу, який володіє мільйонами мов. Незважаючи на його схильність до зайвого занепокоєння і балакучості, він залишається вірним супутником і часто робить несподіваний внесок у успіх місій. Його взаємодії з Р2-Д2 додають гумору до сагу.",
        characters_phrases_that_change_all_h2: "Фрази, які змінили все",
        characters_phrases_that_change_all_p: "«Я твій батько» — одна з найвідоміших фраз в історії кіно.",
        characters_quotes_moments_h2: "Цитати та моменти",
        characters_quotes_moments_p: "Небагато фільмів можуть похвалитися такими знаковими моментами та фразами, як:",
        characters_list_of_quotes_moments_quote_1_li: `<strong>"Нехай буде з тобою Сила."</strong> — Одна з найвідоміших фраз франшизи, яку вимовляють джедаї та їхні союзники.`,
        characters_list_of_quotes_moments_quote_2_li: `<strong>"Допоможи мені, Обі-Ван Кенобі. Ти моя остання надія."</strong> — Лея`,
        characters_list_of_quotes_moments_quote_3_li: `<strong>"Пам'ятай: страх - це шлях на темний бік"</strong> - (Епізод I: Прихована загроза)<br>Йода пояснює, як страх призводить до страждань.`,
        characters_list_of_quotes_moments_quote_4_li: `<strong>Відкриваючі титри</strong> - Кожну частину супроводжує текст, що йде в зоряний простір, з епічною музикою Джона Вільямса.`,
        characters_list_of_quotes_moments_quote_5_li: `<strong>Руйнування Зірки Смерті</strong> - (Епізод IV та Епізод VI)<br>Люк знищує першу Зірку Смерті, а пізніше Повстанці — другу.`,
        characters_list_of_quotes_moments_quote_6_li: `<strong>Дуель на Мустафарі</strong> - (Епізод III: Помста сітхів)<br>Епічна битва між Обі-Ваном та Енакіном на лавовій планеті, де останній остаточно стає Дартом Вейдером.`,
        characters_list_of_quotes_moments_quote_7_li: `<strong>Поява Дарта Мола з подвійним світловим мечем</strong> - (Епізод I: Прихована загроза)<br>Вражаючий момент, що підкреслює міць сітху.`,
        characters_list_of_quotes_moments_quote_8_li: `<strong>Смерть Дарта Вейдера та порятунок Люка</strong> - (Епізод VI: Повернення джедаю)<br>Вейдер рятує Люка від Імператора і вмирає, спокутувавши свої гріхи.`,
        ships_title: `Космічні кораблі`,
        ships_spaceships_h1: `Космічні кораблі`,
        ships_nav_ships_fighters_a: `Винищувачі`,
        ships_nav_ships_freighters_a: `Вантажні кораблі`,
        ships_nav_ships_destroyers_a: `Зоряні руйнівники`,
        ships_fighters_fighters_h2: `Винищувачі`,
        ships_fighters_X_Wing_h2: `X-Wing/Хрестокрил`,
        ships_fighters_X_Wing_p: `<strong>Опис:</strong> Винищувачі X-wing були розроблені 
        для повітряних боїв та тривалих місій. Під час Галактичної 
        громадянської війни Альянс повстанців використовував моделі винищувачів X-wing, 
        такі як винищувач T-65B X-wing та T-65C-A2 X-wing у багатьох 
        битвах, розгортаючи X-wing у таких битвах, як Атака на Лотал, 
        Битва при Явині, Битва при Ендорі та Битва за Джакку.`,
        ships_fighters_X_Wing_length_p: `<strong>Довжина:</strong> 12,5 м`,
        ships_fighters_X_Wing_armament_p: `<strong>Озброєння:</strong> Лазерні гармати, протонні торпеди`,
        ships_fighters_TIE_Fighter_h3: `TIE-Винищувач`,
        ships_fighters_TIE_Fighter_p: `<strong>Опис:</strong> Винищувач космічної переваги TIE/ln,
        зазвичай званий винищувачем TIE/LN, винищувачем TIE/line,
        винищувачем TIE або T/F, був стандартним імперським винищувачем,
        який можна було побачити у величезних кількостях протягом
        більшу частину Галактичної громадянської війни і далі. Іноді,
        через їхню відмінну форму, пілоти повстанців та Нової Республіки
        називали цей корабель «очними яблуками».`,
        ships_fighters_TIE_Fighter_length_p: `<strong>Довжина:</strong> 8,99 м`,
        ships_fighters_TIE_Fighter_armament_p: `<strong>Озброєння:</strong> Лазерні гармати`,
        ships_freighters_freighters_h2: `Вантажні кораблі`,
        ships_freighters_Millennium_Falcon_h3: `Тисячолітній Сокіл`,
        ships_freighters_Millennium_Falcon_p: `<strong>Опис:</strong> Тисячолітній сокіл, спочатку позначений як YT 492727ZED і раніше 
        відомий як Stellar Envoy, та зареєстрований або відомий під різними псевдонімами, був 
        корелліанським легким вантажним судном YT-1300, збудованим близько 60 років до битви при Явіні. Заробивши 
        легендарний статус під своїм володінням, корабель найбільш відомий тим, що використовувався 
        контрабандистами Ханом Соло та Чубаккою до, під час та після Галактичної громадянської війни.`,
        ships_freighters_Millennium_Falcon_length_p: `<strong>Довжина:</strong> 34,75 м`,
        ships_freighters_Millennium_Falcon_armament_p: `<strong>Особливість:</strong> Кесельський пробіг за 12 парсеків.`,
        ships_destroyers_destroyers_h2: `Зоряні руйнівники`,
        ships_destroyers_Imperial_Star_Destroyer_h3: `Імперський Зоряний Руйнівник`,
        ships_destroyers_Imperial_Star_Destroyer_p: `<strong>Опис:</strong> Головний військовий корабель Імперського флоту та символ 
        Імперської мощі.Ці величезні капітальні кораблі використовуються для виконання волі Імператора, 
        підтримки підтримуваних Імперією урядів і виступають як 
        мобільних штабів старших імперських командирів. Вважається, що одного зіркового руйнівника достатньо, 
        щоб розтрощити бунтівну планету, хоча великі індустріальні світи можуть бути 
        атаковані флотом із шести Зоряних Руйнівників з крейсерами підтримки та судами 
        постачання. Бункери для виживання, що глибоко залягають, вважаються останнім притулком 
        у разі планетарного бомбардування Імперськими Зоряними руйнівниками.`,
        ships_destroyers_Imperial_Star_Destroyer_length_p: `<strong>Довжина:</strong> 1,600 м`,
        ships_destroyers_Imperial_Star_Destroyer_armament_p: `<strong>Озброєння:</strong> Лазерні турелі, іонні гармати, тяговий промінь`,
        contacts_title: `Контакти`,
        contacts_contacts_h1: `Контакти`,
        contacts_contact_us_h2: `Зв'яжіться з нами`,
        contacts_contact_us_p: `Якщо у вас є запитання чи пропозиції, напишіть нам поштою <a href="playeralex2006@gmail.com">playeralex2006@gmail.com</a> або знайдіть нас у соцмережах.`,
        
    }
};

//Массивы данных для перевода <iframe>

var iframeData = {
    en: {
        iframe1: "https://www.youtube.com/embed/bD7bpG-zDJQ",
        iframe2: "https://www.youtube.com/embed/JNwNXF9Y6kY?si=52qss3EZ12KLfqeB"
    },
    ru: {
        iframe1: "https://www.youtube.com/embed/omuTFYiVqgA?si=yUsSqoi0oZZFRaCD",
        iframe2: "https://www.youtube.com/embed/7ZjN5TiYzuI?si=cfZGfOREcpqr3LYx"
    },
    uk: {
        iframe1: "https://www.youtube.com/embed/T1M62rntzhI?si=Z0i1c-XvkRhFtIau",
        iframe2: "https://www.youtube.com/embed/QHMy8I0NxfE?si=liJImx_noMq5yQnB" // Временная ссылка
    }
};
